### ISSUE TITLE
How to calculate breath rate and SPO2?

### ISSUE THREAD

**Issue by bbbbbrenn** [pi-null-mezon/vpglib#5]
Excuse me.I know this project is extracted from QPULSECAPTURE,that project included breath rate and SPO2,but vpg only include heart rate,could you tell me how to do it?

**Comment by pi-null-mezon** [comment]
@bbbbbrenn unfortunately SPO2 level could not be measured by means of ordinary web cam. QPULSECAPTURE was designed as an experiment to check this out. On the other hand breath rate seems to could be measured. Not directly from the videoplethysmographyc signal (note, that QPULSECAPTURE uses such naive approach, and it is not accurate) but from the blood pulse waves duration. I am working on breath rate, but this functionality will be added only and if I could get robust and accurate measurements.

**Comment by bbbbbrenn** [comment]
Thank you vary much!

**Comment by andy78lecce** [comment]
Hi, first of all thanks a lot for your code.
I have an application (written in c#) that evaluate in real time the facial expression of a subject in front of a webcam. Now, my idea is to monitor HR and to evaluate if a specific HR pattern is associated to a specific facial expression.
Since my code is in c#, can you suggest me a software/tips for using your library?
Thanks in advance.

**Comment by pi-null-mezon** [comment]
Hello @andy78lecce, You can build a shared library (dll if you work in MS Windows) from my code. Then it could be used from almost any language/framework. To build vpglib into shared library you need only c++ compiller and opencv binaries.

**Comment by vickyhexr** [comment]
Hi @pi-null-mezon can i measure respiration rate from Web cam??
