### ISSUE TITLE
Measure reasonable HR values even using a picture.

### ISSUE THREAD

**Issue by uncleyoung** [pi-null-mezon/vpglib#7]
Hi, thanks for this nice work.
I've played around with the Examples/hrvanalyser. But when I hold a picture of face in front of the camera, it still reports a reasonable heart beat rate.
Is it supposed to be like that, or I've made something wrong ?

**Comment by pi-null-mezon** [comment]
Hello. Yes I know about that issue. Basically it is because processing pipeline can not resolve face reflectance changes related to head motions/illumination changes and true blood filling. So in your case one of the motion harmonics has been returned I guess. To partially suppress such false-positive measurements you can try to play with the [SNR](https://github.com/pi-null-mezon/vpglib/blob/e42e91f2f64a07858de4d66a0aac1853d8e94b27/Library/include/pulseprocessor.h#L106). But in general vpglib can not be used as liveness detector. At least for now.

**Comment by uncleyoung** [comment]
many thanks for your reply. I'll close this issue.
